/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedJoinRouteImport } from './routes/_authenticated/join'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups/index'
import { Route as AuthenticatedGroupsDiscoverRouteImport } from './routes/_authenticated/groups/discover'
import { Route as AuthenticatedGroupsGroupIdIndexRouteImport } from './routes/_authenticated/groups/$groupId/index'
import { Route as AuthenticatedGroupsGroupIdExpensesNewRouteImport } from './routes/_authenticated/groups/$groupId/expenses/new'
import { Route as AuthenticatedGroupsGroupIdExpensesExpenseIdIndexRouteImport } from './routes/_authenticated/groups/$groupId/expenses/$expenseId/index'
import { Route as AuthenticatedGroupsGroupIdExpensesExpenseIdEditRouteImport } from './routes/_authenticated/groups/$groupId/expenses/$expenseId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJoinRoute = AuthenticatedJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsDiscoverRoute =
  AuthenticatedGroupsDiscoverRouteImport.update({
    id: '/groups/discover',
    path: '/groups/discover',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsGroupIdIndexRoute =
  AuthenticatedGroupsGroupIdIndexRouteImport.update({
    id: '/groups/$groupId/',
    path: '/groups/$groupId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsGroupIdExpensesNewRoute =
  AuthenticatedGroupsGroupIdExpensesNewRouteImport.update({
    id: '/groups/$groupId/expenses/new',
    path: '/groups/$groupId/expenses/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsGroupIdExpensesExpenseIdIndexRoute =
  AuthenticatedGroupsGroupIdExpensesExpenseIdIndexRouteImport.update({
    id: '/groups/$groupId/expenses/$expenseId/',
    path: '/groups/$groupId/expenses/$expenseId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsGroupIdExpensesExpenseIdEditRoute =
  AuthenticatedGroupsGroupIdExpensesExpenseIdEditRouteImport.update({
    id: '/groups/$groupId/expenses/$expenseId/edit',
    path: '/groups/$groupId/expenses/$expenseId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/join': typeof AuthenticatedJoinRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/groups/discover': typeof AuthenticatedGroupsDiscoverRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/groups/$groupId/': typeof AuthenticatedGroupsGroupIdIndexRoute
  '/groups/$groupId/expenses/new': typeof AuthenticatedGroupsGroupIdExpensesNewRoute
  '/groups/$groupId/expenses/$expenseId/edit': typeof AuthenticatedGroupsGroupIdExpensesExpenseIdEditRoute
  '/groups/$groupId/expenses/$expenseId/': typeof AuthenticatedGroupsGroupIdExpensesExpenseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/join': typeof AuthenticatedJoinRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/groups/discover': typeof AuthenticatedGroupsDiscoverRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdIndexRoute
  '/groups/$groupId/expenses/new': typeof AuthenticatedGroupsGroupIdExpensesNewRoute
  '/groups/$groupId/expenses/$expenseId/edit': typeof AuthenticatedGroupsGroupIdExpensesExpenseIdEditRoute
  '/groups/$groupId/expenses/$expenseId': typeof AuthenticatedGroupsGroupIdExpensesExpenseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/join': typeof AuthenticatedJoinRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/groups/discover': typeof AuthenticatedGroupsDiscoverRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/groups/$groupId/': typeof AuthenticatedGroupsGroupIdIndexRoute
  '/_authenticated/groups/$groupId/expenses/new': typeof AuthenticatedGroupsGroupIdExpensesNewRoute
  '/_authenticated/groups/$groupId/expenses/$expenseId/edit': typeof AuthenticatedGroupsGroupIdExpensesExpenseIdEditRoute
  '/_authenticated/groups/$groupId/expenses/$expenseId/': typeof AuthenticatedGroupsGroupIdExpensesExpenseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/join'
    | '/profile'
    | '/groups/discover'
    | '/groups/'
    | '/groups/$groupId/'
    | '/groups/$groupId/expenses/new'
    | '/groups/$groupId/expenses/$expenseId/edit'
    | '/groups/$groupId/expenses/$expenseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/join'
    | '/profile'
    | '/groups/discover'
    | '/groups'
    | '/groups/$groupId'
    | '/groups/$groupId/expenses/new'
    | '/groups/$groupId/expenses/$expenseId/edit'
    | '/groups/$groupId/expenses/$expenseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/join'
    | '/_authenticated/profile'
    | '/_authenticated/groups/discover'
    | '/_authenticated/groups/'
    | '/_authenticated/groups/$groupId/'
    | '/_authenticated/groups/$groupId/expenses/new'
    | '/_authenticated/groups/$groupId/expenses/$expenseId/edit'
    | '/_authenticated/groups/$groupId/expenses/$expenseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/join': {
      id: '/_authenticated/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthenticatedJoinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/discover': {
      id: '/_authenticated/groups/discover'
      path: '/groups/discover'
      fullPath: '/groups/discover'
      preLoaderRoute: typeof AuthenticatedGroupsDiscoverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/$groupId/': {
      id: '/_authenticated/groups/$groupId/'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/$groupId/expenses/new': {
      id: '/_authenticated/groups/$groupId/expenses/new'
      path: '/groups/$groupId/expenses/new'
      fullPath: '/groups/$groupId/expenses/new'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdExpensesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/$groupId/expenses/$expenseId/': {
      id: '/_authenticated/groups/$groupId/expenses/$expenseId/'
      path: '/groups/$groupId/expenses/$expenseId'
      fullPath: '/groups/$groupId/expenses/$expenseId/'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdExpensesExpenseIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/$groupId/expenses/$expenseId/edit': {
      id: '/_authenticated/groups/$groupId/expenses/$expenseId/edit'
      path: '/groups/$groupId/expenses/$expenseId/edit'
      fullPath: '/groups/$groupId/expenses/$expenseId/edit'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdExpensesExpenseIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJoinRoute: typeof AuthenticatedJoinRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedGroupsDiscoverRoute: typeof AuthenticatedGroupsDiscoverRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedGroupsGroupIdIndexRoute: typeof AuthenticatedGroupsGroupIdIndexRoute
  AuthenticatedGroupsGroupIdExpensesNewRoute: typeof AuthenticatedGroupsGroupIdExpensesNewRoute
  AuthenticatedGroupsGroupIdExpensesExpenseIdEditRoute: typeof AuthenticatedGroupsGroupIdExpensesExpenseIdEditRoute
  AuthenticatedGroupsGroupIdExpensesExpenseIdIndexRoute: typeof AuthenticatedGroupsGroupIdExpensesExpenseIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJoinRoute: AuthenticatedJoinRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedGroupsDiscoverRoute: AuthenticatedGroupsDiscoverRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedGroupsGroupIdIndexRoute: AuthenticatedGroupsGroupIdIndexRoute,
  AuthenticatedGroupsGroupIdExpensesNewRoute:
    AuthenticatedGroupsGroupIdExpensesNewRoute,
  AuthenticatedGroupsGroupIdExpensesExpenseIdEditRoute:
    AuthenticatedGroupsGroupIdExpensesExpenseIdEditRoute,
  AuthenticatedGroupsGroupIdExpensesExpenseIdIndexRoute:
    AuthenticatedGroupsGroupIdExpensesExpenseIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
